version: '3'

services:

  # Gitea: Git server
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"  # Gitea web UI
      - "22:22"       # Gitea SSH
    restart: always
    networks:
      - ci_cd_network

  # Jenkins: CI server
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"  # Jenkins web UI
      - "50000:50000"  # Jenkins agent connection
    restart: always
    networks:
      - ci_cd_network

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
    restart: always

#  # Nexus Repository: Artifact repository
#  nexus:
#    image: sonatype/nexus3
#    container_name: nexus
#    ports:
#      - "8081:8081"  # Nexus web UI
#    volumes:
#      - nexus_data:/nexus-data
#    restart: always
#    networks:
#      - ci_cd_network

volumes:
  gitea_data:
  jenkins_data:
  nexus-data:

networks:
  ci_cd_network:
    driver: bridge


