name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  # Update these to match your existing Nexus configuration
  NEXUS_URL: http://localhost:8081  # Replace with your Nexus host/ip
  NEXUS_REPOSITORY: maven-snapshots
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verify Nexus connectivity
        run: |
          echo "Testing Nexus connection..."
          curl -v $NEXUS_URL/service/rest/v1/status
          echo "Checking repository exists..."
          curl -u admin:${{ secrets.NEXUS_PASSWORD }} \
            "$NEXUS_URL/service/rest/v1/repositories" | jq '.[] | select(.name == "$NEXUS_REPOSITORY")'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>admin</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>nexus</id>
                <url>$NEXUS_URL/repository/maven-public/</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>
          EOF

      - name: Build and deploy
        run: |
          mvn -B clean deploy \
            -DaltDeploymentRepository=nexus::default::$NEXUS_URL/repository/$NEXUS_REPOSITORY \
            -DrepositoryId=nexus

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t bojjana/my-image:latest .
          docker push bojjana/my-image:latest
