name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      nexus:
        image: sonatype/nexus3:3.41.1
        ports:
          - 8081:8081
        env:
          NEXUS_ADMIN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        options: >-
          --health-cmd="curl -f http://localhost:8081/service/rest/v1/status || exit 1"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=10
          --health-start-period=60s

    env:
      NEXUS_URL: http://localhost:8081
      NEXUS_REPO_URL: http://localhost:8081/repository/maven-snapshots
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Wait for Nexus to be ready
        run: |
          echo "Waiting for Nexus to be ready..."
          for i in {1..30}; do
            if curl -sSf -u admin:${{ secrets.NEXUS_PASSWORD }} \
              "$NEXUS_URL/service/rest/v1/status" | grep -q "state\":\"RUNNING"; then
              echo "Nexus is ready!"
              break
            fi
            echo "Attempt $i/30: Nexus not ready yet..."
            sleep 10
          done

          echo "Verifying maven-snapshots repository exists..."
          curl -u admin:${{ secrets.NEXUS_PASSWORD }} \
            "$NEXUS_URL/service/rest/v1/repositories" | jq '.[] | select(.name == "maven-snapshots")'

      - name: Configure Maven settings
        run: |
          cat <<EOF > settings.xml
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>admin</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>nexus</id>
                <url>$NEXUS_URL/repository/maven-public/</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>
          EOF
          mkdir -p ~/.m2
          mv settings.xml ~/.m2/

      - name: Build with Maven
        run: mvn -B clean package

      - name: Deploy to Nexus
        run: |
          echo "Deploying to $NEXUS_REPO_URL"
          mvn -B deploy \
            -DaltDeploymentRepository=nexus::default::$NEXUS_REPO_URL \
            -DrepositoryId=nexus \
            -DretryFailedDeploymentCount=3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t bojjana/my-image:latest .

      - name: Push Docker Image
        run: docker push bojjana/my-image:latest
