name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      nexus:
        image: sonatype/nexus3
        ports:
          - 8081:8081
        env:
          NEXUS_ADMIN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        options: >-
          --health-cmd="curl -f http://localhost:8081 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      NEXUS_URL: http://localhost:8081
      NEXUS_REPOSITORY: maven-snapshots
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.8.7'

      - name: Wait for Nexus to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8081 >/dev/null; then
              echo "Nexus is ready!"
              break
            fi
            echo "Waiting for Nexus to start..."
            sleep 10
          done

      - name: Build with Maven
        run: mvn clean install

      - name: Configure Maven for Nexus
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>admin</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF
          
      - name: Deploy to Nexus
        run: |
          #Verify repository exists
           if ! curl -sSf -u admin:${{ secrets.NEXUS_PASSWORD }} \
            "$NEXUS_URL/service/rest/v1/repositories/maven-snapshots" > /dev/null; then
             echo "ERROR: maven-snapshots repository not found or inaccessible!"
              exit 1
          fi
  
    # Deploy with debug info
    mvn -B deploy \
      -DaltDeploymentRepository=nexus::default::$NEXUS_URL/repository/maven-snapshots \
      -DrepositoryId=nexus

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t bojjana/my-image:latest .

      - name: Push Docker Image
        run: docker push bojjana/my-image:latest
